<?php
ob_start();
require("../connection.php");
include("./layouts/header.php");
include("./layouts/nav.php");
include("./layouts/error.php");
include("./layouts/pages.php");
include("./layouts/footer.php");
?>